spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: false

app:
  seed:
    enabled: ${APP_SEED_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_EXPOSURE:health}
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.project_kata.global_invoices_kata_mngr: INFO
    org.springframework.security: WARN
